In [7]:
import pandas as pd 
import numpy as np

In [29]:
df = pd.read_csv("C:/Users/HP/Downloads/archive (21)/Diwali Sales Data.csv" , encoding = 'latin1')

In [31]:
df.head(10)

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.00,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.00,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.00,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.00,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.00,NaN,NaN
5,1000588,Joni,P00057942,M,26-35,28,1,Himachal Pradesh,Northern,Food Processing,Auto,1,23877.00,NaN,NaN
6,1001132,Balk,P00018042,F,18-25,25,1,Uttar Pradesh,Central,Lawyer,Auto,4,23841.00,NaN,NaN
7,1002092,Shivangi,P00273442,F,55+,61,0,Maharashtra,Western,IT Sector,Auto,1,NaN,NaN,NaN
8,1003224,Kushal,P00205642,M,26-35,35,0,Uttar Pradesh,Central,Govt,Auto,2,23809.00,NaN,NaN
9,1003650,Ginny,P00031142,F,26-35,26,1,Andhra Pradesh,Southern,Media,Auto,4,23799.99,NaN,NaN

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
 13  Status            0 non-null      float64
 14  unnamed1          0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 1.3+ MB

In [35]:
#drop unneccsesary columns
df.drop(['Status', 'unnamed1'], axis = 1, inplace = True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11239 non-null  float64
dtypes: float64(1), int64(4), object(8)
memory usage: 1.1+ MB

In [39]:
#remove duplicates 
df.duplicated().sum()

8

In [41]:
df.isnull().sum()
df.isnull().sum()[df.isnull().sum()> 1]

Amount    12
dtype: int64

In [43]:
cat_cols = ['Amount']
for cols in cat_cols:
    df['Amount'].fillna('Not available', inplace = True)

C:\Users\HP\AppData\Local\Temp\ipykernel_23940\4223646472.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amount'].fillna('Not available', inplace = True)
C:\Users\HP\AppData\Local\Temp\ipykernel_23940\4223646472.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Amount'].fillna('Not available', inplace = True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11251 entries, 0 to 11250
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User_ID           11251 non-null  int64
 1   Cust_name         11251 non-null  object
 2   Product_ID        11251 non-null  object
 3   Gender            11251 non-null  object
 4   Age Group         11251 non-null  object
 5   Age               11251 non-null  int64
 6   Marital_Status    11251 non-null  int64
 7   State             11251 non-null  object
 8   Zone              11251 non-null  object
 9   Occupation        11251 non-null  object
 10  Product_Category  11251 non-null  object
 11  Orders            11251 non-null  int64
 12  Amount            11251 non-null  object
dtypes: int64(4), object(9)
memory usage: 1.1+ MB

In [47]:
df['Marital_Status'] = df['Marital_Status'].replace({ 1 : 'married' , 0 : 'unmarried'})

In [49]:
df.head(10)

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,F,26-35,28,unmarried,Maharashtra,Western,Healthcare,Auto,1,23952.0
1,1000732,Kartik,P00110942,F,26-35,35,married,Andhra Pradesh,Southern,Govt,Auto,3,23934.0
2,1001990,Bindu,P00118542,F,26-35,35,married,Uttar Pradesh,Central,Automobile,Auto,3,23924.0
3,1001425,Sudevi,P00237842,M,0-17,16,unmarried,Karnataka,Southern,Construction,Auto,2,23912.0
4,1000588,Joni,P00057942,M,26-35,28,married,Gujarat,Western,Food Processing,Auto,2,23877.0
5,1000588,Joni,P00057942,M,26-35,28,married,Himachal Pradesh,Northern,Food Processing,Auto,1,23877.0
6,1001132,Balk,P00018042,F,18-25,25,married,Uttar Pradesh,Central,Lawyer,Auto,4,23841.0
7,1002092,Shivangi,P00273442,F,55+,61,unmarried,Maharashtra,Western,IT Sector,Auto,1,Not available
8,1003224,Kushal,P00205642,M,26-35,35,unmarried,Uttar Pradesh,Central,Govt,Auto,2,23809.0
9,1003650,Ginny,P00031142,F,26-35,26,married,Andhra Pradesh,Southern,Media,Auto,4,23799.99

In [51]:
#save new csv file
df.to_csv('diwali_new.csv', index = False)

In [17]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-py2.py3-none-any.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-py2.py3-none-any.whl (480 kB)
   ---------------------------------------- 0.0/480.6 kB ? eta -:--:--
   - ------------------------------------- 20.5/480.6 kB 640.0 kB/s eta 0:00:01
   -- ------------------------------------ 30.7/480.6 kB 640.0 kB/s eta 0:00:01
   ---- ---------------------------------- 51.2/480.6 kB 327.7 kB/s eta 0:00:02
   ------- ------------------------------- 92.2/480.6 kB 521.8 kB/s eta 0:00:01
   ------- ------------------------------- 92.2/480.6 kB 521.8 kB/s eta 0:00:01
   --------------- ---------------------- 194.6/480.6 kB 692.9 kB/s eta 0:00:01
   ----------------- -------------------- 225.3/480.6 kB 762.6 kB/s eta 0:00:01
   ------------------------ ------------- 307.2/480.6 kB 824.9 kB/s eta 0:00:01
   ---------------------------------------  471.0/480.6 kB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 480.6/480.6 kB 1.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [55]:
import mysql.connector
from sqlalchemy import create_engine

engine = create_engine('mysql+mysqlconnector://root:DHNiv#1107@localhost/new_schema1')

df.to_sql('diwali_new', engine, if_exists='replace', index=False)

print("Done")

Done